### ISSUE TITLE
`getAgentConfig` is not a function in `1.48.x`

### ISSUE THREAD

**Issue by grenik** [SAP/cloud-sdk-js#1568]
**Describe the bug**
Problems with the `getAgentConfig` import: getting the error `getAgentConfig` is not a function.
Shall we import it somehow differently now?
It works with `1.47.1` and is not working with the later versions
```json
{
   "error":{
      
   },
   "level":"error",
   "message":"uncaughtException: getAgentConfig is not a function\nTypeError: getAgentConfig is not a function\n    at Object.<anonymous> (/home/vcap/app/extractors/failer.js:3:1)\n    at Module._compile (internal/modules/cjs/loader.js:1068:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47",
   "stack":"TypeError: getAgentConfig is not a function\n    at Object.<anonymous> (/home/vcap/app/extractors/failer.js:3:1)\n    at Module._compile (internal/modules/cjs/loader.js:1068:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47",
   "exception":true,
   "date":"Thu Sep 02 2021 11:26:41 GMT+0000 (Coordinated Universal Time)",
   "process":{
      "pid":7,
      "uid":2000,
      "gid":2000,
      "cwd":"/home/vcap/app",
      "execPath":"/home/vcap/deps/0/node/bin/node",
      "version":"v14.17.0",
      "argv":[
         "/home/vcap/deps/0/node/bin/node",
         "/home/vcap/app/extractors/failer"
      ],
      "memoryUsage":{
         "rss":58626048,
         "heapTotal":20283392,
         "heapUsed":14520448,
         "external":1607528,
         "arrayBuffers":196066
      }
   },
   "os":{
      "loadavg":[
         2.34,
         2.58,
         2.24
      ],
      "uptime":97139.73
   },
   "trace":[
      {
         "column":1,
         "file":"/home/vcap/app/extractors/failer.js",
         "function":null,
         "line":3,
         "method":null,
         "native":false
      },
      {
         "column":30,
         "file":"internal/modules/cjs/loader.js",
         "function":"Module._compile",
         "line":1068,
         "method":"_compile",
         "native":false
      },
      {
         "column":10,
         "file":"internal/modules/cjs/loader.js",
         "function":"Module._extensions..js",
         "line":1097,
         "method":".js",
         "native":false
      },
      {
         "column":32,
         "file":"internal/modules/cjs/loader.js",
         "function":"Module.load",
         "line":933,
         "method":"load",
         "native":false
      },
      {
         "column":14,
         "file":"internal/modules/cjs/loader.js",
         "function":"Module._load",
         "line":774,
         "method":"_load",
         "native":false
      },
      {
         "column":12,
         "file":"internal/modules/run_main.js",
         "function":"Function.executeUserEntryPoint [as runMain]",
         "line":72,
         "method":"executeUserEntryPoint [as runMain]",
         "native":false
      },
      {
         "column":47,
         "file":"internal/main/run_main_module.js",
         "function":null,
         "line":17,
         "method":null,
         "native":false
      }
   ],
   "logger":"sap-cloud-sdk-logger",
   "test":"exception",
   "timestamp":"2021-09-02T11:26:41.153Z",
   "msg":"TypeError: getAgentConfig is not a function\n    at Object.<anonymous> (/home/vcap/app/extractors/failer.js:3:1)\n    at Module._compile (internal/modules/cjs/loader.js:1068:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n    at Module.load (internal/modules/cjs/loader.js:933:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47",
   "written_ts":1630582001153,
   "written_at":"2021-09-02T11:26:41.153Z"
}
```

**To Reproduce**

Run the following code:
```js
const { getAgentConfig } = require('@sap-cloud-sdk/core');
const destinationName = (process.argv.length > 2) ? process.argv[2] : "your default destination name";
getAgentConfig(destinationName);
```

**Expected behavior**
No error

**Used Versions:**

- node version via `node -v` `14.17.0`
- npm version via `npm -v` `6.14.13`
- SAP Cloud SDK version you used as dependency `1.48.1`

**Comment by jjtang1985** [comment]
Hi @grenik ,

Thanks for reporting this issue.
I opened a PR for fixing it.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @grenik ,

The PR is merged and you can try the `canary` version.
A new stable version should be released soon.

I'll close the ticket and please reopen if necessary.
